# Generated by Django 3.2.24 on 2024-02-20 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('createrId', models.CharField(max_length=50)),
                ('sharedUserIds', models.TextField()),
                ('tmsCreate', models.IntegerField()),
                ('tmsUpdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorId', models.CharField(max_length=50)),
                ('versionNumber', models.IntegerField()),
                ('addedLines', models.TextField()),
                ('editedLines', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='note',
            name='history',
            field=models.ManyToManyField(to='NotesApi.VersionHistory'),
        ),
    ]
