# Generated by Django 3.2.24 on 2024-02-20 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApi', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionhistory',
            name='tmsUpdate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
