# Generated by Django 3.2.24 on 2024-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApi', '0004_versionhistory_tmsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sharedUserIds',
            field=models.TextField(default='[]'),
        ),
    ]
