# Generated by Django 3.2.24 on 2024-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApi', '0005_alter_note_shareduserids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='history',
            field=models.ManyToManyField(default=None, to='NotesApi.VersionHistory'),
        ),
    ]
