# Generated by Django 3.2.24 on 2024-02-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApi', '0006_alter_note_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='createrId',
            new_name='creatorId',
        ),
    ]
